#!/usr/bin/env python3
"""
Repository to HTML Converter
This script takes a repository directory, traverses all files, and generates
an HTML document containing each file's path and content.
"""
import os
import json
import argparse
import html
import datetime

DEFAULT_CONFIG = {
    "excluded_extensions": [
        ".git",
        ".pyc",
        ".class",
        ".o",
        ".exe",
        ".pdf",
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".ico",
        ".svg",
        ".webp",
        ".bmp",
        ".ttf",
        ".woff",
        ".woff2",
        ".eot",
        ".map",
        ".lock",
    ],
    "excluded_folders": [
        ".git",
        "__pycache__",
        "node_modules",
        "venv",
        "dist",
        "build",
        ".next",
        "out",
        ".vercel",
        ".cache",
        "public/images",
        "public/static",
        "coverage",
        ".vscode",
        "repo-export"
    ],
    "excluded_files": ["pnpm-lock.yaml", ".env.local"],
    "title": "Repository Code Documentation",
    "max_file_size_kb": 500,  # Skip files larger than this size (in KB)
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        header {{
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }}
        h1 {{
            color: #2c3e50;
        }}
        .file-title {{
            background-color: #f0f0f0;
            padding: 10px;
            margin-top: 30px;
            margin-bottom: 5px;
            border-left: 4px solid #3498db;
            font-weight: bold;
            font-family: monospace;
            word-break: break-all;
        }}
        .file-content {{
            background-color: #f9f9f9;
            padding: 15px;
            border: 1px solid #eee;
            overflow-x: auto;
            font-family: Consolas, Monaco, 'Andale Mono', monospace;
            font-size: 14px;
            white-space: pre;
        }}
        .toc {{
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 30px;
            border: 1px solid #eee;
        }}
        .toc h2 {{
            margin-top: 0;
        }}
        .toc ul {{
            padding-left: 20px;
        }}
        .toc li {{
            margin-bottom: 5px;
        }}
        .toc a {{
            text-decoration: none;
            color: #3498db;
        }}
        .toc a:hover {{
            text-decoration: underline;
        }}
        .footer {{
            margin-top: 50px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        @media print {{
            .toc {{
                break-after: page;
            }}
            .file-title {{
                break-after: avoid;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <p>Generated on {date}</p>
        </header>
        <div class="toc">
            <h2>Table of Contents</h2>
            <ul>
                {toc_content}
            </ul>
        </div>
        {file_content}
        <div class="footer">
            <p>Generated by Repository to HTML Converter | Created by Nikhil Lakhwani</p>
        </div>
    </div>
</body>
</html>
"""


def load_config(config_path):
    """Load configuration from a JSON file, or return default config if file doesn't exist."""
    try:
        with open(config_path, "r") as config_file:
            user_config = json.load(config_file)
            # Merge with default config, keeping user settings where provided
            config = DEFAULT_CONFIG.copy()
            config.update(user_config)
            # Store the config file path in the config itself for exclusion purposes
            config["config_file_path"] = config_path
            return config
    except (FileNotFoundError, json.JSONDecodeError):
        print(f"Config file not found or invalid. Using default configuration.")
        config = DEFAULT_CONFIG.copy()
        config["config_file_path"] = config_path
        return config


def should_include_file(file_path, config):
    """Determine if a file should be included based on configuration."""
    # Skip the script itself
    if os.path.basename(file_path) == os.path.basename(__file__):
        return False

    # Skip the config file
    if os.path.basename(file_path) == os.path.basename(
        config.get("config_file_path", "repo_to_html.json")
    ):
        return False

    # Check for specific excluded files
    rel_path = os.path.basename(file_path)
    if rel_path in config.get("excluded_files", []):
        return False

    # Also check full relative path for more specific exclusion
    repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if os.path.isdir(repo_dir):
        try:
            rel_path = os.path.relpath(file_path, repo_dir)
            if rel_path in config.get("excluded_files", []):
                return False
        except ValueError:
            # This happens if the file is on a different drive than the repo on Windows
            pass

    # Check file extension
    _, ext = os.path.splitext(file_path)
    if ext in config["excluded_extensions"]:
        return False

    # Check if file is in excluded folder
    path_parts = file_path.split(os.sep)
    for part in path_parts:
        if part in config["excluded_folders"]:
            return False

    # Check file size
    try:
        file_size_kb = os.path.getsize(file_path) / 1024
        if file_size_kb > config["max_file_size_kb"]:
            print(f"Skipping large file: {file_path} ({file_size_kb:.2f} KB)")
            return False
    except OSError:
        print(f"Error getting size of {file_path}, skipping")
        return False

    return True


def create_html(repo_dir, output_path, config):
    """Create an HTML file containing all repository files."""
    files_data = []
    toc_items = []
    file_count = 0

    # Traverse the repository
    for root, dirs, files in os.walk(repo_dir):
        # Filter out excluded directories
        dirs[:] = [d for d in dirs if d not in config["excluded_folders"]]

        # Sort files to have a consistent order
        files.sort()

        for file in files:
            file_path = os.path.join(root, file)
            rel_path = os.path.relpath(file_path, repo_dir)

            if not should_include_file(file_path, config):
                continue

            file_count += 1
            file_id = f"file-{file_count}"

            try:
                # Read file content
                with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                    content = f.read()

                # Add to files data
                files_data.append({"id": file_id, "path": rel_path, "content": content})

                # Add to TOC
                toc_items.append(
                    f'<li><a href="#{file_id}">{html.escape(rel_path)}</a></li>'
                )
            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    # Generate TOC content
    toc_content = "\n".join(toc_items)

    # Generate files content
    file_content_html = ""
    for file_data in files_data:
        file_content_html += f'<div class="file-title" id="{file_data["id"]}">{html.escape(file_data["path"])}</div>\n'
        file_content_html += (
            f'<div class="file-content">{html.escape(file_data["content"])}</div>\n\n'
        )

    # Fill template
    html_content = HTML_TEMPLATE.format(
        title=html.escape(config.get("title", "Repository Code Documentation")),
        date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        toc_content=toc_content,
        file_content=file_content_html,
    )

    # Write to file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(f"Processed {file_count} files")
    print(f"HTML created successfully: {output_path}")


def create_default_config(config_path):
    """Create a default configuration file."""
    with open(config_path, "w") as config_file:
        json.dump(DEFAULT_CONFIG, config_file, indent=4)
    print(f"Default configuration created: {config_path}")


def main():
    """Main function handling command line arguments."""
    parser = argparse.ArgumentParser(
        description="Convert repository files to an HTML document"
    )
    parser.add_argument(
        "repo_dir",
        help='Path to the repository directory (use "." for current directory)',
    )
    parser.add_argument(
        "--output", "-o", default="repository.html", help="Output HTML file path"
    )
    parser.add_argument(
        "--config", "-c", default="repo_to_html.json", help="Configuration file path"
    )
    parser.add_argument(
        "--create-config",
        action="store_true",
        help="Create a default configuration file",
    )

    args = parser.parse_args()

    if args.create_config:
        create_default_config(args.config)
        return

    # Convert to absolute paths
    repo_dir = os.path.abspath(args.repo_dir)
    output_path = os.path.abspath(args.output)
    config_path = os.path.abspath(args.config)

    print(f"Repository: {repo_dir}")
    print(f"Output: {output_path}")
    print(f"Config: {config_path}")

    config = load_config(config_path)
    create_html(repo_dir, output_path, config)


if __name__ == "__main__":
    main()
